'use client';
import { useEffect, useRef, useState } from 'react';
import { ArrowUpRight, ChevronDown, ChevronUp, CircleHelp, Compass, Focus, Maximize, Minus, Orbit, Pause, Play, Plus, RotateCcw, SlidersHorizontal, X } from 'lucide-react';
import { Slider } from '@/components/ui/slider';
import { PlanetDetailsDialog } from './planet-details-dialog';
import { PlanetImage } from './planet-image';
import { SpaceExplorer } from './space-explorer';
import { defaultSpaceLayers, spaceObjectById, type SpaceLayers } from './space-data';
import { Dialog, DialogClose, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { flushSync } from 'react-dom';
import { Switch } from '@/components/ui/switch';
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group';
import { languageStorageKey, localizedBodies, translate, type Language } from './i18n';
import { bodies } from './solar-data';
import { SolarScene, type SceneAPI } from './solar-scene';
export default function Home() {
 const host=useRef<HTMLDivElement>(null), api=useRef<SceneAPI|null>(null), selectedRef=useRef(-1);
 const [dockCollapsed,setDockCollapsed]=useState(false);
 const [selected,setSelected]=useState(-1),[paused,setPaused]=useState(false),[speed,setSpeed]=useState(20),[labels,setLabels]=useState(true),[orbits,setOrbits]=useState(true),[settings,setSettings]=useState(false),[help,setHelp]=useState(false),[days,setDays]=useState(0),[error,setError]=useState('');
 const [spaceLayers,setSpaceLayers]=useState<SpaceLayers>(defaultSpaceLayers),[selectedObject,setSelectedObject]=useState<string|null>(null);
 const [language,setLanguage]=useState<Language>('en'),[languageReady,setLanguageReady]=useState(false);
 const t=(text:string)=>translate(language,text);
 const visibleBodies=localizedBodies(language);
 useEffect(()=>{try{const saved=localStorage.getItem(languageStorageKey);if(saved==='en'||saved==='vi')setLanguage(saved);}catch{}setLanguageReady(true);},[]);
 useEffect(()=>{if(!languageReady)return;try{localStorage.setItem(languageStorageKey,language);}catch{}document.documentElement.lang=language;document.title=language==='vi'?'Orbit — Đài quan sát Hệ Mặt Trời':'Orbit — Solar Observatory';api.current?.setLanguage(language);},[language,languageReady]);
 const choose=(i:number)=>{setSelectedObject(null);selectedRef.current=i;setSelected(i);api.current?.focus(i);};
 const chooseObject=(id:string)=>{const item=spaceObjectById.get(id);if(!item)return;setSelectedObject(id);selectedRef.current=-1;setSelected(-1);setSpaceLayers(previous=>({...previous,[item.layer]:true}));if(item.layer==='missions')setSpeed(1/1440);else if(item.layer==='moons')setSpeed(.03);api.current?.focusObject(id);};
 const changeLayers=(layers:SpaceLayers)=>{setSpaceLayers(layers);if(selectedObject&&!layers[spaceObjectById.get(selectedObject)!.layer])choose(-1);};
 useEffect(()=>{api.current?.setLayers(spaceLayers);},[spaceLayers]);
 useEffect(()=>{if(!host.current)return;try{api.current=new SolarScene(host.current,i=>{setSelectedObject(null);selectedRef.current=i;setSelected(i);},setDays,chooseObject);}catch{setError('The 3D view needs WebGL. Enable hardware acceleration in your browser, then reload.');}return()=>api.current?.dispose();},[]);
 useEffect(()=>{api.current?.configure({paused,speed,labels,orbits});},[paused,speed,labels,orbits]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.defaultPrevented||(e.target as HTMLElement).closest('input,button,[role="slider"],[role="switch"],[role="dialog"]'))return;if(e.code==='Space'){e.preventDefault();setPaused(p=>!p);}if(e.key==='Escape')choose(-1);if(e.key==='ArrowRight')choose((selectedRef.current+1)%bodies.length);if(e.key==='ArrowLeft')choose((selectedRef.current+bodies.length-1)%bodies.length);};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[]);
 useEffect(()=>{
  type Tool={name:string;description:string;inputSchema:object;annotations:{readOnlyHint:boolean};execute:(input:unknown)=>unknown};
  const context=(document as Document & {modelContext?:{registerTool:(tool:Tool,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;
  if(!context?.registerTool)return;const lifecycle=new AbortController();
  const register=(tool:Tool)=>{try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}};
  register({name:'navigate_solar_system',description:'Select a world and smoothly move the camera to follow it, or return to overview.',inputSchema:{type:'object',properties:{body:{type:'string',enum:['Overview',...bodies.map(b=>b.name)]}},required:['body'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){const value=input as {body?:string};const i=value?.body==='Overview'?-1:bodies.findIndex(b=>b.name===value?.body);if(i<0&&value?.body!=='Overview')throw new Error('Choose a valid body or Overview.');flushSync(()=>choose(i));return {selected:value.body,camera:'transitioning',facts:i>=0?bodies[i]:null};}});
  register({name:'configure_simulation_time',description:'Set playback and the number of simulated Earth days per second.',inputSchema:{type:'object',properties:{paused:{type:'boolean'},daysPerSecond:{type:'number',minimum:0.000011574074074074073,maximum:200}},required:['paused','daysPerSecond'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){const v=input as {paused?:boolean;daysPerSecond?:number};if(typeof v?.paused!=='boolean'||typeof v.daysPerSecond!=='number'||!Number.isFinite(v.daysPerSecond)||v.daysPerSecond<1/86400||v.daysPerSecond>200)throw new Error('Supply paused and a speed from 1/86400 to 200 days per second.');flushSync(()=>{setPaused(v.paused!);setSpeed(v.daysPerSecond!);});return {paused:v.paused,daysPerSecond:v.daysPerSecond};}});
  return()=>lifecycle.abort();
 },[]);
 const b=selected>=0?visibleBodies[selected]:null;
 return <main className={`observatory dark ${selectedObject?'has-space-selection':''} ${dockCollapsed?'dock-collapsed':''}`}><div ref={host} className="universe" aria-label={t("Interactive three-dimensional solar system")}/>{error&&<div className="scene-error" role="alert">{t(error)}<button onClick={()=>location.reload()}>{t("Reload")}</button></div>}
 <header className="masthead"><a href="/" className="brand" aria-label={t("Orbit home")}><Orbit size={30}/><span>ORBIT<span className="brand-dot">.</span></span></a><div className="header-caption">{t("THE SOLAR SYSTEM EXPLORER")}</div><div className="header-actions"><span className="live"><i/>{t("SIMULATION")}</span><button className="icon-button" title={t("How to explore")} aria-label={t("How to explore")} onClick={()=>setHelp(!help)}><CircleHelp size={20}/></button></div></header>
 <SpaceExplorer language={language} layers={spaceLayers} onLayers={changeLayers} selectedId={selectedObject} onSelect={chooseObject} onOverview={()=>choose(-1)}/>
 <section className="intro"><div className="eyebrow"><span className="tiny-line"/>{t("OUR COSMIC NEIGHBORHOOD")}</div><h1>{b?b.name:t("A little perspective.")}</h1><p>{b?b.subtitle:t("One star. Eight worlds. Endless discovery.")}</p><div className="view-tag"><i/>{b?t("FOLLOWING ")+b.name.toUpperCase():t("SOLAR SYSTEM OVERVIEW")}</div>{b&&<PlanetDetailsDialog key={selected} bodyIndex={selected} language={language} className="mobile-details"/>}</section>
 <aside className="readout" aria-live="polite"><div className="readout-heading"><span>{b?t("BODY / ")+String(selected).padStart(2,'0'):t("SYSTEM / 01")}</span><Compass size={18}/></div><h2>{b?b.name:t("The Solar System")}</h2><p>{b?b.description:t("A family of worlds bound by gravity, traveling together around the heart of the Milky Way.")}</p><dl>{b?<><div><dt>{t("Diameter")}</dt><dd>{b.diameter} <small>km</small></dd></div><div><dt>{t("Distance from Sun")}</dt><dd>{b.au} <small>AU</small></dd></div><div><dt>{t("Orbital period")}</dt><dd>{b.year}</dd></div></>:<><div><dt>{t("Our star")}</dt><dd>{t("The Sun")}</dd></div><div><dt>{t("Planets")}</dt><dd>08</dd></div><div><dt>{t("Age")}</dt><dd>{language==='vi'?'4,6':'4.6'} <small>{t("billion years")}</small></dd></div></>}</dl>{b&&<PlanetDetailsDialog key={selected} bodyIndex={selected} language={language}/>}<button className="text-button" onClick={()=>choose(b?-1:3)}>{b?t("Return to overview"):t("Visit our home planet")}<ArrowUpRight size={17}/></button><div className="scale-note">{t("Distances compressed. Bodies enlarged.")}<br/>{t("Orbital periods proportionally preserved.")}</div></aside>
 <div className="camera-tools"><button className="icon-button" title={t("Zoom in")} aria-label={t("Zoom in")} onClick={()=>api.current?.zoom(.8)}><Plus size={19}/></button><button className="icon-button" title={t("Zoom out")} aria-label={t("Zoom out")} onClick={()=>api.current?.zoom(1.25)}><Minus size={19}/></button><span/><button className="icon-button" title={t("Reset camera")} aria-label={t("Reset camera")} onClick={()=>choose(-1)}><Focus size={19}/></button><button className="icon-button" title={t("Top view")} aria-label={t("Top view")} onClick={()=>api.current?.top()}><Compass size={19}/></button></div>
 <div className="scene-hint"><span className="mouse-symbol"/>{t("Drag to orbit")}<span>·</span>{t("Scroll to zoom")}<span>·</span>{t("Select a world")}</div>
 <div className="console-dock"><button className="dock-toggle" aria-expanded={!dockCollapsed} aria-controls="solar-console" aria-label={language==='vi'?(dockCollapsed?'Mở thanh tổng quan':'Thu gọn thanh tổng quan'):(dockCollapsed?'Expand overview bar':'Collapse overview bar')} onClick={()=>{setDockCollapsed(value=>!value);setSettings(false);}}>{dockCollapsed?<ChevronUp size={18}/>:<ChevronDown size={18}/>}<span>{language==='vi'?(dockCollapsed?'Mở tổng quan':'Thu gọn'):(dockCollapsed?'Overview':'Collapse')}</span></button><footer id="solar-console" className="console" inert={dockCollapsed}><div className="planet-strip"><button className={'overview-button '+(selected===-1&&!selectedObject?'active':'')} onClick={()=>choose(-1)}><Orbit size={21}/><span>{t("Overview")}</span></button><div className="planet-list">{visibleBodies.map((p,i)=><button key={p.name} className={'planet-button '+(selected===i?'active':'')} onClick={()=>choose(i)} aria-pressed={selected===i}><PlanetImage bodyIndex={i} className="planet-thumbnail"/><span>{p.name}</span><small>{String(i).padStart(2,'0')}</small></button>)}</div></div><div className="time-bar"><div className="transport"><button className="icon-button" aria-label={t("Reset simulation time")} title={t("Reset simulation time")} onClick={()=>api.current?.resetTime()}><RotateCcw size={16}/></button><button className="play-button" aria-label={paused?t("Play simulation"):t("Pause simulation")} onClick={()=>setPaused(!paused)}>{paused?<Play size={18} fill="currentColor"/>:<Pause size={18} fill="currentColor"/>}</button><div className="time-readout"><span>{t("ELAPSED EARTH DAYS")}</span><strong>{days.toLocaleString(language==='vi'?'vi-VN':'en-US',{maximumFractionDigits:0,minimumIntegerDigits:3})}<i>{paused?t("PAUSED"):t("RUNNING")}</i></strong></div></div><div className="speed-control"><span>{t("Time speed")}</span><Slider aria-label={t("Simulation days per second")} min={0} max={100} step={.1} value={[(Math.log10(speed)+Math.log10(86400))/(Math.log10(200)+Math.log10(86400))*100]} getAriaValueText={()=>speed<1?`${Math.round(speed*86400)} ${language==='vi'?'giây mô phỏng mỗi giây':'simulated seconds per second'}`:`${speed} ${t('d/s')}`} onValueChange={v=>{const n=Array.isArray(v)?v[0]:v;const value=10**(n/100*(Math.log10(200)+Math.log10(86400))-Math.log10(86400));setSpeed(value>=1?Math.round(value):value);}}/><strong>{speed<1?Math.round(speed*86400):speed}<small>{speed<1?'s/s':t("d/s")}</small></strong></div><div className="view-controls"><button className={settings?'active':''} onClick={()=>setSettings(!settings)} aria-expanded={settings}><SlidersHorizontal size={16}/><span>{t("View settings")}</span></button><button className="icon-button" aria-label={t("Toggle fullscreen")} title={t("Fullscreen")} onClick={()=>{if(document.fullscreenElement)document.exitFullscreen().catch(()=>{});else document.documentElement.requestFullscreen?.().catch(()=>{});}}><Maximize size={17}/></button></div></div></footer></div>
 {settings&&<section className="settings-panel"><div className="panel-title">{t("View settings")}<button aria-label={t("Close settings")} onClick={()=>setSettings(false)}><X size={17}/></button></div><fieldset className="language-field"><legend>{t("Language")}</legend><RadioGroup aria-label={t("Language")} value={language} onValueChange={value=>{if(value==='en'||value==='vi')setLanguage(value);}} className="language-options"><label lang="en"><RadioGroupItem value="en" aria-label="English"/><span>English <small>EN</small></span></label><label lang="vi"><RadioGroupItem value="vi" aria-label="Tiếng Việt"/><span>Tiếng Việt <small>VI</small></span></label></RadioGroup></fieldset><div className="space-time-presets"><span>{language==='vi'?'Tốc độ gợi ý':'Time presets'}</span><button onClick={()=>setSpeed(1/1440)}>{language==='vi'?'Trạm · 60×':'Stations · 60×'}</button><button onClick={()=>setSpeed(20)}>{language==='vi'?'Hành tinh · 20 ngày/s':'Planets · 20 d/s'}</button></div><label>{t("Planet labels")}<Switch checked={labels} onCheckedChange={setLabels}/></label><label>{t("Orbital paths")}<Switch checked={orbits} onCheckedChange={setOrbits}/></label><button className="text-button" onClick={()=>{api.current?.top();setSettings(false);}}>{t("View from above")}<ArrowUpRight size={17}/></button></section>}
 <Dialog open={help} onOpenChange={setHelp}><DialogContent className="help-dialog" showCloseButton={false}><DialogClose className="localized-close" aria-label={t("Close")}><X size={18}/></DialogClose><DialogTitle>{t("Your window into space")}</DialogTitle><DialogDescription>{t("Drag to orbit. Scroll or pinch to zoom. Right-drag or use two fingers to pan. Select a world to glide closer and follow its orbit.")}</DialogDescription><div><div className="shortcut"><kbd>Space</kbd>{t("Play / pause")}</div><div className="shortcut"><kbd>← →</kbd>{t("Previous / next world")}</div><div className="shortcut"><kbd>Esc</kbd>{t("System overview")}</div></div><p className="help-note">{t("A scientifically inspired illustration, not a live ephemeris. Starting positions are composed; surfaces are procedural. Rotations and sizes are adjusted for clarity. One AU is the average Earth–Sun distance.")}</p><a href="https://science.nasa.gov/solar-system/" target="_blank" rel="noreferrer">{t("Explore the science at NASA ↗")}</a></DialogContent></Dialog>

 </main>;
}
