import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { localizedBodies, translate, type Language } from './i18n';
import { bodies } from './solar-data';
import { SpaceScene } from './space-scene';
import { spaceObjectById, type SpaceLayers } from './space-data';
export interface SceneAPI { setLanguage(language:Language):void; focus(i:number):void; focusObject(id:string):void; setLayers(layers:SpaceLayers):void;
 configure(v:{paused:boolean;speed:number;labels:boolean;orbits:boolean}):void; zoom(f:number):void; top():void; resetTime():void; dispose():void }
const noise=`
float hash(vec3 p){p=fract(p*.3183099+vec3(.1,.2,.3));p*=17.;return fract(p.x*p.y*p.z*(p.x+p.y+p.z));}
float noise(vec3 p){vec3 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(mix(hash(i),hash(i+vec3(1,0,0)),f.x),mix(hash(i+vec3(0,1,0)),hash(i+vec3(1,1,0)),f.x),f.y),mix(mix(hash(i+vec3(0,0,1)),hash(i+vec3(1,0,1)),f.x),mix(hash(i+vec3(0,1,1)),hash(i+vec3(1,1,1)),f.x),f.y),f.z);}
float fbm(vec3 p){float v=0.,a=.5;for(int i=0;i<5;i++){v+=a*noise(p);p=p*2.03+13.1;a*=.5;}return v;}
`;
const vertex=`varying vec3 vLocal;varying vec3 vNormal;varying vec3 vWorld;void main(){vLocal=normalize(position);vNormal=normalize(mat3(modelMatrix)*normal);vec4 w=modelMatrix*vec4(position,1.);vWorld=w.xyz;gl_Position=projectionMatrix*viewMatrix*w;}`;
const fragment=`uniform vec3 base;uniform float kind;uniform float time;varying vec3 vLocal;varying vec3 vNormal;varying vec3 vWorld;${noise}
void main(){vec3 p=vLocal;float n=fbm(p*8.);vec3 col=base;
if(kind<.5){float hot=fbm(p*19.+time*.018);float cells=noise(p*140.+hot*3.);col=mix(vec3(1.,.18,.015),vec3(1.,.78,.27),hot*.9+cells*.25);float edge=pow(max(0.,dot(normalize(vNormal),normalize(cameraPosition-vWorld))),.3);col*=.72+edge*.6;gl_FragColor=vec4(col*1.8,1.);}
else{if(kind<1.5){float crater=pow(noise(p*100.),3.);col=base*(.5+n*.9-crater*.2);}
else if(kind<2.5){float bands=fbm(p*vec3(5.,19.,5.)+n*2.);col=mix(base*.53,vec3(.91,.75,.48),bands);}
else if(kind<3.5){float land=fbm(p*3.3+vec3(4.,1.,7.));float mask=smoothstep(.48,.52,land);vec3 ground=mix(vec3(.07,.2,.11),vec3(.38,.32,.16),n);col=mix(vec3(.015,.1,.28),ground,mask);float clouds=smoothstep(.58,.75,fbm(p*9.+vec3(time*.004,0.,0.)));col=mix(col,vec3(.86,.9,.92),clouds*.83);col=mix(col,vec3(.82,.91,.94),smoothstep(.89,.97,abs(p.y)));}
else if(kind<4.5){col=base*(.55+n*.8);col=mix(col,vec3(.71,.71,.65),smoothstep(.955,.99,abs(p.y)));}
else if(kind<6.5){float bands=sin(p.y*58.+fbm(p*10.)*5.)*.5+.5;float fine=sin(p.y*180.+n*4.)*.5+.5;col=mix(base*.51,base*1.12,bands*.65+fine*.18+n*.17);if(kind<5.5){float spot=length((p.xy-vec2(.35,-.24))*vec2(5.,12.));float storm=(1.-smoothstep(.6,1.2,spot))*smoothstep(.2,.6,p.z);col=mix(col,vec3(.57,.22,.1),storm*.8);}}
else{col=base*(.79+.16*sin(p.y*22.+n*2.)+n*.2);}
vec3 light=normalize(-vWorld);float diffuse=max(dot(normalize(vNormal),light),0.);float rim=pow(1.-max(dot(normalize(vNormal),normalize(cameraPosition-vWorld)),0.),3.);col*=.13+diffuse*1.2;if(kind>2.5&&kind<3.5)col+=vec3(.09,.27,.54)*rim*.24;gl_FragColor=vec4(col,1.);}
#include <tonemapping_fragment>
#include <colorspace_fragment>
}`;
export class SolarScene implements SceneAPI {
 private backgroundStars?:THREE.Points; private extras!:SpaceScene; private selectedObject:string|null=null;
 private language:Language='en';
 private scene=new THREE.Scene();private camera=new THREE.PerspectiveCamera(43,1,.05,30000);private renderer:THREE.WebGLRenderer;private controls:OrbitControls;
 private groups:THREE.Group[]=[];private planets:THREE.Mesh[]=[];private labelElements:HTMLButtonElement[]=[];private orbitGroup=new THREE.Group();private materials:THREE.ShaderMaterial[]=[];private resizeObserver:ResizeObserver;
 private frame=0;private last=0;private days=0;private lastReadout=0;private selected=-1;private config={paused:false,speed:20,labels:true,orbits:true};private followLast=new THREE.Vector3();private followRadial=new THREE.Vector3();private transition: {start:number;from:THREE.Vector3;target:THREE.Vector3;offset:THREE.Vector3}|null=null;private width=1;private height=1;private reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;private pointer={x:0,y:0};
 constructor(private host:HTMLDivElement,private onSelect:(i:number)=>void,private onTime:(d:number)=>void,private onObjectSelect:(id:string)=>void=()=>{}){
 this.renderer=new THREE.WebGLRenderer({antialias:true,alpha:false,powerPreference:'high-performance'});this.renderer.setClearColor('#06090e');this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.75));this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.15;this.host.appendChild(this.renderer.domElement);
 this.camera.position.set(0,66,104);this.controls=new OrbitControls(this.camera,this.renderer.domElement);this.controls.enableDamping=true;this.controls.dampingFactor=.065;this.controls.minDistance=2;this.controls.maxDistance=260;this.controls.maxPolarAngle=Math.PI*.94;this.controls.zoomSpeed=.8;this.controls.addEventListener('start',this.cancelTransition);
 this.scene.add(this.orbitGroup);this.createStars();this.createBodies();this.extras=new SpaceScene(this.host,this.groups,id=>{this.focusObject(id);this.onObjectSelect(id);});this.scene.add(this.extras.root);this.resizeObserver=new ResizeObserver(this.resize);this.resizeObserver.observe(host);this.resize();this.renderer.domElement.addEventListener('pointerdown',this.pointerDown);this.renderer.domElement.addEventListener('pointerup',this.pointerUp);this.renderer.domElement.addEventListener('webglcontextlost',this.contextLost);document.addEventListener('visibilitychange',this.visibility);this.updatePositions();this.frame=requestAnimationFrame(this.animate);
 }
 private contextLost=(e:Event)=>{e.preventDefault();this.config.paused=true;const message=document.createElement('div');message.className='scene-error';message.setAttribute('role','alert');message.textContent=translate(this.language,'The graphics connection was interrupted. Reload the page to resume exploring.');this.host.appendChild(message);};
 private visibility=()=>{this.last=0;};
 private resize=()=>{this.width=this.host.clientWidth;this.height=this.host.clientHeight;this.camera.aspect=this.width/this.height;this.camera.setViewOffset(this.width,this.height,this.width>760?this.width*.09:0,0,this.width,this.height);this.camera.updateProjectionMatrix();this.renderer.setSize(this.width,this.height);};
 private createStars(){let seed=12345;const rand=()=>{seed=(seed*16807)%2147483647;return seed/2147483647;};const count=2600,p=new Float32Array(count*3),c=new Float32Array(count*3);for(let i=0;i<count;i++){const z=rand()*2-1,a=rand()*Math.PI*2,r=350+rand()*300,s=Math.sqrt(1-z*z);p.set([r*s*Math.cos(a),r*z,r*s*Math.sin(a)],i*3);const brightness=.25+rand()*.6;c.set([brightness*.83,brightness*.88,brightness],i*3);}const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.BufferAttribute(p,3));geometry.setAttribute('color',new THREE.BufferAttribute(c,3));this.backgroundStars=new THREE.Points(geometry,new THREE.PointsMaterial({size:.65,sizeAttenuation:true,vertexColors:true,transparent:true,opacity:.72,depthWrite:false}));this.scene.add(this.backgroundStars);}
 private createBodies(){bodies.forEach((b,i)=>{const group=new THREE.Group();this.scene.add(group);this.groups.push(group);const axis=new THREE.Group();axis.rotation.z=THREE.MathUtils.degToRad(b.tilt);group.add(axis);const mat=new THREE.ShaderMaterial({vertexShader:vertex,fragmentShader:fragment,uniforms:{base:{value:new THREE.Color(b.color)},kind:{value:i},time:{value:0}}});this.materials.push(mat);const mesh=new THREE.Mesh(new THREE.SphereGeometry(b.radius,64,40),mat);mesh.userData.index=i;axis.add(mesh);this.planets.push(mesh);
 if(i===0){const canvas=document.createElement('canvas');canvas.width=canvas.height=256;const ctx=canvas.getContext('2d')!;const gradient=ctx.createRadialGradient(128,128,0,128,128,128);gradient.addColorStop(0,'rgba(255,214,140,.55)');gradient.addColorStop(.2,'rgba(255,177,69,.36)');gradient.addColorStop(.42,'rgba(246,115,27,.09)');gradient.addColorStop(1,'rgba(244,108,19,0)');ctx.fillStyle=gradient;ctx.fillRect(0,0,256,256);const sprite=new THREE.Sprite(new THREE.SpriteMaterial({map:new THREE.CanvasTexture(canvas),transparent:true,blending:THREE.AdditiveBlending,depthWrite:false}));sprite.scale.set(36,36,1);group.add(sprite);}
 if(i===3||i>=5){const atmosphere=new THREE.Mesh(new THREE.SphereGeometry(b.radius*1.028,48,32),new THREE.ShaderMaterial({vertexShader:vertex,fragmentShader:`varying vec3 vNormal;varying vec3 vWorld;uniform vec3 tint;void main(){float rim=pow(1.-abs(dot(normalize(vNormal),normalize(cameraPosition-vWorld))),3.);float lit=.2+max(dot(normalize(vNormal),normalize(-vWorld)),0.);gl_FragColor=vec4(tint,rim*lit*.38);}`,uniforms:{tint:{value:new THREE.Color(i===3?'#6dacff':b.color)}},transparent:true,depthWrite:false,blending:THREE.AdditiveBlending}));group.add(atmosphere);}
 if(i===6){const ring=new THREE.Mesh(new THREE.RingGeometry(b.radius*1.3,b.radius*2.35,192),new THREE.ShaderMaterial({vertexShader:`varying vec3 pos;void main(){pos=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}`,fragmentShader:`varying vec3 pos;void main(){float r=length(pos.xy);float f=sin(r*105.)*.15+sin(r*210.)*.1+.7;float gap=smoothstep(.055,.09,abs(r-3.93));float edge=smoothstep(2.73,2.83,r)*(1.-smoothstep(4.75,4.935,r));gl_FragColor=vec4(vec3(.59,.51,.37)*f,f*gap*edge*.85);}`,side:THREE.DoubleSide,transparent:true,depthWrite:false}));ring.rotation.x=-Math.PI/2;axis.add(ring);}
 if(i>0){const points=[];for(let k=0;k<=256;k++){const a=k/256*Math.PI*2;points.push(new THREE.Vector3(Math.cos(a)*b.distance,0,Math.sin(a)*b.distance));}const line=new THREE.LineLoop(new THREE.BufferGeometry().setFromPoints(points),new THREE.LineBasicMaterial({color:i===3?'#7b98b6':'#586271',transparent:true,opacity:i===3?.29:.19}));this.orbitGroup.add(line);}
 const label=document.createElement('button');label.className='planet-label';label.textContent=b.name;label.setAttribute('aria-label','Explore '+b.name);label.addEventListener('click',()=>{this.focus(i);this.onSelect(i);});this.host.appendChild(label);this.labelElements.push(label);
 });}
 private updatePositions(){this.groups.forEach((g,i)=>{const b=bodies[i],angle=b.phase-this.days/b.period*Math.PI*2;g.position.set(Math.cos(angle)*b.distance,0,Math.sin(angle)*b.distance);this.planets[i].rotation.y=this.days*.035;this.materials[i].uniforms.time.value=this.days*.02;});this.extras.update(this.days,this.config.orbits);}
 private animate=(time:number)=>{this.frame=requestAnimationFrame(this.animate);if(document.hidden)return;const delta=this.last?Math.min((time-this.last)/1000,.06):0;this.last=time;if(!this.config.paused)this.days+=delta*this.config.speed;this.updatePositions();
 if(this.transition){const tr=this.transition,t=this.reduced?1:Math.min((time-tr.start)/1600,1),ease=t*t*(3-2*t),target=this.focusPosition();this.controls.target.lerpVectors(tr.target,target,ease);this.camera.position.lerpVectors(tr.from,target.clone().add(tr.offset),ease);if(t>=1){this.transition=null;this.followLast.copy(target);this.syncRadial();this.controls.maxDistance=this.selectedObject&&spaceObjectById.get(this.selectedObject)?.layer==='sky'?14000:260;}}
 else if(this.selected>=0||this.selectedObject){const pos=this.focusPosition(),change=pos.clone().sub(this.followLast);this.camera.position.add(change);this.controls.target.add(change);if(this.selectedObject&&spaceObjectById.get(this.selectedObject)?.orbit){const orbit=spaceObjectById.get(this.selectedObject)!.orbit!,radial=pos.clone().sub(this.groups[orbit.parent].position).normalize();const rotation=new THREE.Quaternion().setFromUnitVectors(this.followRadial,radial);this.camera.position.sub(this.controls.target).applyQuaternion(rotation).add(this.controls.target);this.followRadial.copy(radial);}this.followLast.copy(pos);}
 this.controls.update();this.renderer.render(this.scene,this.camera);this.updateLabels();this.extras.updateLabels(this.camera,this.width,this.height,this.config.labels);if(time-this.lastReadout>200){this.onTime(this.days);this.lastReadout=time;}};
 private updateLabels(){this.groups.forEach((g,i)=>{const label=this.labelElements[i],p=g.position.clone();p.y+=bodies[i].radius+1.1;p.project(this.camera);const x=(p.x*.5+.5)*this.width,y=(-p.y*.5+.5)*this.height;const visible=this.config.labels&&!(this.selectedObject&&spaceObjectById.get(this.selectedObject)?.layer==='sky')&&p.z<1&&p.z>-1&&x>10&&x<this.width-10&&y>85&&y<this.height-205&&(this.selected<0||i===this.selected||this.camera.position.distanceTo(g.position)<45);label.style.display=visible?'block':'none';if(visible){label.style.left=x+'px';label.style.top=y+'px';label.classList.toggle('selected',i===this.selected);}});}
 private pointerDown=(e:PointerEvent)=>{this.pointer={x:e.clientX,y:e.clientY};};
 private pointerUp=(e:PointerEvent)=>{if(e.button!==0||Math.hypot(e.clientX-this.pointer.x,e.clientY-this.pointer.y)>5)return;const rect=this.renderer.domElement.getBoundingClientRect(),mouse=new THREE.Vector2((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1),ray=new THREE.Raycaster();ray.setFromCamera(mouse,this.camera);const hit=ray.intersectObjects([...this.planets,...this.extras.pickables],false).find(h=>!h.object.userData.spaceId||this.extras.isVisible(h.object.userData.spaceId));if(hit){const id=hit.object.userData.spaceId;if(id){this.focusObject(id);this.onObjectSelect(id);}else{const i=hit.object.userData.index;this.focus(i);this.onSelect(i);}}};
 private syncRadial(){const orbit=this.selectedObject?spaceObjectById.get(this.selectedObject)?.orbit:undefined;if(orbit)this.followRadial.copy(this.focusPosition()).sub(this.groups[orbit.parent].position).normalize();}
 private cancelTransition=()=>{this.syncRadial();this.transition=null;if(this.selected>=0||this.selectedObject)this.followLast.copy(this.focusPosition());};
 focus(i:number){if(i< -1||i>=bodies.length)return;this.selected=i;this.selectedObject=null;this.extras.clearSelection();this.controls.maxDistance=20000;const radius=i<0?0:bodies[i].radius;this.controls.minDistance=i<0?2:radius*1.7;const offset=i<0?new THREE.Vector3(0,66,104):new THREE.Vector3(radius*3.9,radius*2.1,radius*6.3);this.transition={start:performance.now(),from:this.camera.position.clone(),target:this.controls.target.clone(),offset};}
 private focusPosition(){return this.selectedObject?this.extras.position(this.selectedObject):this.selected<0?new THREE.Vector3():this.groups[this.selected].position.clone();}
 focusObject(id:string){const item=spaceObjectById.get(id);if(!item)return;this.selected=-1;this.selectedObject=id;this.extras.focus(id);const sky=item.layer==='sky';const radius=item.orbit?.size??1;this.controls.minDistance=sky?2:Math.max(radius*2,.3);this.controls.maxDistance=20000;
 const offset=sky?this.extras.position(id).normalize().multiplyScalar(-8950):this.extras.position(id).sub(this.groups[item.orbit!.parent].position).normalize().multiplyScalar(Math.max(radius*9,1.9)).add(new THREE.Vector3(.4,.6,.4));this.transition={start:performance.now(),from:this.camera.position.clone(),target:this.controls.target.clone(),offset};}
 setLayers(layers:SpaceLayers){this.extras.configure(layers);if(this.backgroundStars)this.backgroundStars.visible=layers.sky;}
 setLanguage(language:Language){this.language=language;this.extras.setLanguage(language);const localized=localizedBodies(language);this.labelElements.forEach((label,i)=>{label.textContent=localized[i].name;label.setAttribute('aria-label',translate(language,'Explore ')+localized[i].name);});const error=this.host.querySelector('.scene-error');if(error)error.textContent=translate(language,'The graphics connection was interrupted. Reload the page to resume exploring.');}
 configure(v:{paused:boolean;speed:number;labels:boolean;orbits:boolean}){this.config=v;this.orbitGroup.visible=v.orbits;}
 zoom(f:number){this.cancelTransition();const offset=this.camera.position.clone().sub(this.controls.target);offset.setLength(THREE.MathUtils.clamp(offset.length()*f,this.controls.minDistance,this.controls.maxDistance));this.camera.position.copy(this.controls.target).add(offset);}
 top(){this.transition={start:performance.now(),from:this.camera.position.clone(),target:this.controls.target.clone(),offset:this.selectedObject&&spaceObjectById.get(this.selectedObject)?.layer==='sky'?this.extras.position(this.selectedObject).normalize().multiplyScalar(-8950):new THREE.Vector3(0,this.selectedObject?4:this.selected<0?125:bodies[this.selected].radius*8,.01)};}
 resetTime(){this.cancelTransition();this.days=0;this.updatePositions();if(this.selected>=0||this.selectedObject){const next=this.focusPosition(),change=next.clone().sub(this.followLast);this.controls.target.add(change);this.camera.position.add(change);this.followLast.copy(next);this.syncRadial();}this.onTime(0);}
 dispose(){this.extras.dispose();cancelAnimationFrame(this.frame);this.resizeObserver.disconnect();document.removeEventListener('visibilitychange',this.visibility);this.renderer.domElement.removeEventListener('pointerdown',this.pointerDown);this.renderer.domElement.removeEventListener('pointerup',this.pointerUp);this.renderer.domElement.removeEventListener('webglcontextlost',this.contextLost);this.controls.dispose();this.scene.traverse(o=>{const mesh=o as THREE.Mesh;if(mesh.geometry)mesh.geometry.dispose();if(mesh.material){for(const m of Array.isArray(mesh.material)?mesh.material:[mesh.material]){const material=m as THREE.MeshBasicMaterial;material.map?.dispose();material.dispose();}}});this.renderer.dispose();this.labelElements.forEach(l=>l.remove());this.renderer.domElement.remove();}
}
