export const bodies=[
{name:'Sun',subtitle:'The star at the center of it all.',color:'#ffbc62',radius:4.3,distance:0,period:1,phase:0,tilt:7.25,diameter:'1,392,700',au:'0',year:'—',description:'A sphere of incandescent plasma that holds the solar system together. Nuclear fusion in its core supplies the light and warmth that make life on Earth possible.'},
{name:'Mercury',subtitle:'Small world. Swift journey.',color:'#a8a39a',radius:.55,distance:8,period:87.97,phase:1.8,tilt:.03,diameter:'4,879',au:'0.39',year:'88 days',description:'The smallest planet races around the Sun in just 88 Earth days. Its ancient, cratered surface records billions of years of impacts.'},
{name:'Venus',subtitle:'A world beneath a veil.',color:'#dfb77b',radius:.85,distance:11.5,period:224.7,phase:3.7,tilt:177.4,diameter:'12,104',au:'0.72',year:'225 days',description:'Wrapped in thick clouds of sulfuric acid, Venus has a crushing carbon dioxide atmosphere. A powerful greenhouse effect makes it the hottest planet.'},
{name:'Earth',subtitle:'Our pale blue home.',color:'#6cafdf',radius:.95,distance:15.5,period:365.26,phase:.65,tilt:23.44,diameter:'12,756',au:'1.00',year:'365.26 days',description:'Liquid oceans, shifting continents, and a protective atmosphere make our home a remarkable world. It is the only planet known to host life.'},
{name:'Mars',subtitle:'The next horizon.',color:'#c67754',radius:.7,distance:20,period:686.98,phase:2.8,tilt:25.2,diameter:'6,792',au:'1.52',year:'687 days',description:'Rust-colored deserts stretch across this cold, rocky world. Ancient riverbeds and polar ice preserve clues to a wetter past.'},
{name:'Jupiter',subtitle:'A giant among worlds.',color:'#d7b398',radius:2.5,distance:29,period:4332.59,phase:5.65,tilt:3.13,diameter:'142,984',au:'5.20',year:'11.86 years',description:'More massive than all the other planets combined, Jupiter is a gas giant striped with fast-moving clouds. Vast storms churn through its atmosphere.'},
{name:'Saturn',subtitle:'The jewel of the solar system.',color:'#dac795',radius:2.1,distance:40,period:10759.22,phase:2.45,tilt:26.73,diameter:'120,536',au:'9.58',year:'29.46 years',description:'A spectacular system of icy rings encircles this gas giant. Saturn is so diffuse that its average density is lower than that of water.'},
{name:'Uranus',subtitle:'A world turned on its side.',color:'#9cd5dc',radius:1.45,distance:50,period:30688.5,phase:4.05,tilt:97.77,diameter:'51,118',au:'19.2',year:'84 years',description:'This pale blue ice giant rolls around the Sun on its side. Methane in its atmosphere absorbs red light, lending the planet its blue-green appearance.'},
{name:'Neptune',subtitle:'At the edge of the planetary realm.',color:'#5485df',radius:1.4,distance:60,period:60182,phase:.2,tilt:28.32,diameter:'49,528',au:'30.1',year:'164.8 years',description:'Dark, cold, and swept by powerful winds, Neptune travels a vast orbit. Sunlight takes more than four hours to reach this distant ice giant.'}
];
